chore: add a regression test for #15786 (#24658)
- Code is legit and should work.
- The error was indeed present in `3.1.3` and not present anymore:
```scala
exception occurred while compiling test.scala
java.lang.AssertionError: assertion failed: method $anonfun while compiling test.scala
Exception in thread "main" java.lang.AssertionError: assertion failed: method $anonfun
        at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
        at dotty.tools.dotc.core.tasty.TreePickler.pickleDef(TreePickler.scala:324)
        at dotty.tools.dotc.core.tasty.TreePickler.pickleTree(TreePickler.scala:559)
        at dotty.tools.dotc.core.tasty.TreePickler.pickleTree$$anonfun$9$$anonfun$1(TreePickler.scala:468)
```

Closes #15786
[Cherry-picked c9309e730b6a261ea9ccc0ba86ca7de59ef3bd59]