Fix override checking for Java methods with covariant array
Fixes #24074

When resolving overloads from Java interfaces, treat arrays as
covariant.
This fixes incorrect method selection when multiple Java interfaces override methods with array return types.

Previously, in the example below, we get the compilation error:

```
value foo is not a member of org.test.Test2.A
    lvl3.foo.head.foo()
```

```java
public class JavaPart {
    public interface A { }
    public interface B extends A {
        int onlyInB();
    }
    public interface Lvl1 {
        A[] getData();
    }
    public interface Lvl2 extends Lvl1 {
        @Override
        B[] getData();
    }
    public interface Lvl3 extends Lvl2, Lvl1 { }
}
```

```scala
def test(lvl3: JavaPart.Lvl3): Unit =
  lvl3.getData.head.onlyInB()
```

because `Denotations#mergeSingleDenot` creates a `JointRefDenotation`
for `Lvl1.getData: A[]` and `Lvl2.getData: B[]`,
with a return type of `JArray[A] & JArray[B]`
(since the compiler doesn't recognize that `Lvl2.getData` overrides `Lvl1.getData`).

And because `JArray` isn't recognized as covariant,
`JArray[A & B] <: JArray[A] & JArray[B]` cannot be derived.

Consequently, `lvl3.getData.head` returns a value typed as
`A` instead of neither `B` nor `A & B`,
which fails to resolve the method `onlyInB`.

[Cherry-picked ed3f18d270ccc72853cc015c7129f2f09325aac0][modified]